FROM adoptopenjdk/openjdk8:alpine
WORKDIR /app
ADD ./target/video_processing_service-0.0.1-SNAPSHOT.jar ./video-processing-service.jar
RUN apk update
RUN apk add ffmpeg
RUN ffmpeg -version
CMD java -jar video-processing-service.jar




