# Services
apiVersion: v1
kind: Service
metadata:
    name: videomanagementservice
spec:
    ports:
     - port: 8080
    selector:
      app: videoserver-vms
---
apiVersion: v1
kind: Service
metadata:
    name: metrics
spec:
    ports:
     - port: 8070
    selector:
      app: videoserver-apigw
---
apiVersion: v1
kind: Service
metadata:
    name: videoprocessingservice
spec:
    ports:
     - port: 8090
    selector:
      app: videoserver-vps
---
apiVersion: v1
kind: Service
metadata:
    name: database
spec:
    ports:
     - port: 3306
    selector: 
      app: videoserver-db
---
apiVersion: v1
kind: Service
metadata:
    name: apigw
spec:
    type: LoadBalancer
    ports:
      - port: 8070
        protocol: TCP
        targetPort: 8070
        name: apigw
    selector:
      app: videoserver-apigw
---
apiVersion: v1
kind: Service
metadata:
    name: prometheus
spec:
    type: LoadBalancer
    ports:
      - port: 9090
        protocol: TCP
        targetPort: 9090
        name: prometheus
    selector:
      app: videoserver-prometheus
---
# Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoserver-db
spec:
  selector:
    matchLabels:
      app: videoserver-db
  template:
    metadata:
      labels:
        app: videoserver-db
    spec:
      containers:
      - name: database
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: video_manager
          - name: MYSQL_USER
            value: springuser
          - name: MYSQL_PASSWORD
            value: DS2019!
          - name: MYSQL_ROOT_PASSWORD
            value: root
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoserver-vms
spec:
  selector:
    matchLabels:
      app: videoserver-vms
  template:
    metadata:
      labels:
        app: videoserver-vms
    spec:
        containers: 
        - name: videomanagementservice
          image: vms1:hw1
          ports:
          - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: database
            - name: DATASOURCE_URL
              value: jdbc:mysql://database:3306/video_manager
            - name: DATASOURCE_USER
              value: springuser
            - name: DATASOURCE_PASSWORD
              value: DS2019!
          volumeMounts:
              - mountPath: /app/var 
                name: vms-storage
        volumes:
        - name: vms-storage
          hostPath:
              path: /storage
              type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoserver-vps
spec:
  selector:
    matchLabels:
      app: videoserver-vps
  template:
      metadata:
        labels:
          app: videoserver-vps
      spec:
        containers:
        - name: videoprocessingservice
          image: vps:hw1
          ports:
          - containerPort: 8090
          volumeMounts:
              - mountPath: /app/var 
                name: vps-storage
        volumes:
        - name: vps-storage
          hostPath:
              path: /storage
              type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoserver-apigw
spec:
  selector:
    matchLabels:
      app: videoserver-apigw
  template:
      metadata:
        labels:
          app: videoserver-apigw
      spec:
        containers:
        - name: apigw
          image: apigw:hw1
          ports:
          - containerPort: 8070
          volumeMounts:
              - mountPath: /app/var 
                name: apigw-storage
        volumes:
        - name: apigw-storage
          hostPath:
              path: /storage
              type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoserver-prometheus
spec:
  selector:
    matchLabels:
      app: videoserver-prometheus
  template:
      metadata:
        labels:
          app: videoserver-prometheus
      spec:
        containers:
        - name: prometheus
          image: prom/prometheus
          ports:
          - containerPort: 9090
          volumeMounts:
              - mountPath: /etc/prometheus/prometheus.yml
                name: prometheus-config
          #command: ["--config.file=/etc/prometheus/prometheus.yml"]
        volumes:
        - name: prometheus-config
          hostPath:
              path: /storage/Prometheus/prometheus.yml
              type: File

  
